spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.5.94:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.94:8848
      config:
        server-addr: 192.168.5.94:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 192.168.5.94
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.5.94
    port: 6379
  cache:
    type: redis
    redis:
      #      生存周期
      time-to-live: 3600000
      #      使用前缀
      use-key-prefix: true
      #      允许空值，防止缓存穿透
      cache-null-values: true
  session:
    store-type: redis
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000