spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.94:8848
      config:
        server-addr: 192.168.5.94:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.5.94
    port: 6379
  session:
    store-type: redis
server:
  port: 12000